version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: 'root'
      LANG: C.UTF-8
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./database/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
      - ./database/conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  app:
    build: .
    ports:
      - '5000:5000'
volumes:
  my-db: